import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ru' | 'ky';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.transactions': 'Transactions',
    'nav.reports': 'Reports',
    'nav.chatbot': 'AI Assistant',
    'nav.settings': 'Settings',
    'nav.help': 'Help',
    'nav.logout': 'Logout',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.no_notifications': 'No notifications',
    'notifications.monthly_report': 'Monthly Report',
    'notifications.report_ready': 'Your monthly financial report is ready',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Your business financial overview',
    'dashboard.total_income': 'Total Income',
    'dashboard.total_expenses': 'Total Expenses',
    'dashboard.net_profit': 'Net Profit',
    'dashboard.recent_transactions': 'Recent Transactions',
    'dashboard.view_all': 'View All',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.new_transaction': 'New Transaction',
    'dashboard.generate_report': 'Generate Report',
    'dashboard.ask_ai': 'Ask AI Assistant',
    'dashboard.expense_chart': 'Expenses by Category',
    'dashboard.expenses_by_category': 'Expenses by Category',
    'dashboard.income_vs_expenses': 'Income vs Expenses',
    'dashboard.no_data': 'No data available',
    'dashboard.add_transactions_first': 'Add some transactions to see charts',
    'dashboard.income': 'Income',
    'dashboard.expenses': 'Expenses',
    'dashboard.amount': 'Amount',
    'dashboard.last_30_days': 'Last 30 days',
    'dashboard.last_7_days': 'Last 7 days',
    'dashboard.last_3_months': 'Last 3 months',
    
    // Chatbot
    'chatbot.subtitle': 'AI-powered financial analysis and advice',
    'chatbot.welcome': 'Hello! I\'m your AI financial assistant. I can analyze your transactions and provide insights about your business finances. What would you like to know?',
    'chatbot.ai_assistant': 'AI Assistant',
    'chatbot.online': 'Online',
    'chatbot.type_message': 'Type your message...',
    'chatbot.quick_questions': 'Quick questions you can ask:',
    'chatbot.quick_income': 'How much income do I have?',
    'chatbot.quick_expenses': 'What are my biggest expenses?',
    'chatbot.quick_profit': 'What is my profit this month?',
    'chatbot.quick_advice': 'Give me financial advice',
    'chatbot.income_analysis': 'Your total income is',
    'chatbot.income_positive': 'Great job on generating revenue!',
    'chatbot.income_zero': 'You haven\'t recorded any income yet. Start adding your sales and revenue transactions.',
    'chatbot.expense_analysis': 'Your total expenses are',
    'chatbot.expense_high': 'Your expenses are higher than your income. Consider reviewing your spending.',
    'chatbot.expense_good': 'Your expenses are well controlled compared to your income.',
    'chatbot.profit_analysis': 'Your net profit is',
    'chatbot.profit_positive': 'Excellent! You\'re making a profit. Consider investing in growth.',
    'chatbot.profit_negative': 'You\'re currently at a loss. Focus on increasing income or reducing expenses.',
    'chatbot.profit_zero': 'You\'re breaking even. Look for opportunities to increase profitability.',
    'chatbot.category_analysis': 'Your highest expense category is',
    'chatbot.no_expenses': 'You haven\'t recorded any expenses yet.',
    'chatbot.advice_negative': 'To improve your finances: 1) Review and cut unnecessary expenses, 2) Focus on increasing sales, 3) Consider new revenue streams.',
    'chatbot.advice_positive': 'Great financial health! Consider: 1) Reinvesting profits for growth, 2) Building an emergency fund, 3) Exploring new markets.',
    'chatbot.advice_neutral': 'To grow your business: 1) Analyze which products/services are most profitable, 2) Invest in marketing, 3) Optimize your pricing.',
    'chatbot.transaction_count': 'You have',
    'chatbot.transaction_recent': 'Keep tracking your transactions for better insights!',
    'chatbot.transaction_none': 'Start adding transactions to get personalized financial insights.',
    'chatbot.default_response': 'I can help you analyze your income, expenses, profit, and provide financial advice. Try asking about your financial performance or request specific insights!',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.business_name': 'Business Name',
    'auth.phone': 'Phone Number',
    'auth.language': 'Language',
    'auth.create_account': 'Create Account',
    'auth.have_account': 'Already have an account?',
    'auth.no_account': "Don't have an account?",
    'auth.sign_in': 'Sign In',
    'auth.sign_up': 'Sign Up',
    
    // Transactions
    'transactions.subtitle': 'All your business transactions',
    'transactions.new_transaction': 'New Transaction',
    'transactions.edit_transaction': 'Edit Transaction',
    'transactions.search_placeholder': 'Search transactions...',
    'transactions.all': 'All',
    'transactions.income': 'Income',
    'transactions.expense': 'Expense',
    'transactions.date': 'Date',
    'transactions.description': 'Description',
    'transactions.category': 'Category',
    'transactions.payment_method': 'Payment Method',
    'transactions.amount': 'Amount',
    'transactions.actions': 'Actions',
    'transactions.type': 'Type',
    'transactions.select_category': 'Select category',
    'transactions.description_placeholder': 'Enter transaction description',
    'transactions.tax_relevant': 'Tax relevant',
    'transactions.confirm_delete': 'Are you sure you want to delete this transaction?',
    'transactions.no_transactions': 'No transactions yet',
    'transactions.add_first_transaction': 'Add your first transaction to get started',
    'transactions.no_results': 'No transactions found matching your search',
    'transactions.payment_methods.cash': 'Cash',
    'transactions.payment_methods.card': 'Bank Card',
    'transactions.payment_methods.transfer': 'Bank Transfer',
    'transactions.payment_methods.mobile': 'Mobile Payment',
    'transactions.calendar': 'Calendar View',
    'transactions.calendar_view': 'Transaction Calendar',
    'transactions.has_transactions': 'Has transactions',
    'transactions.selected_date': 'Selected date',
    'transactions.date_range': 'Date range',
    'transactions.selected_range': 'Selected Range',
    'transactions.apply_filter': 'Apply Filter',
    
    // Reports
    'reports.subtitle': 'Detailed analysis of your business',
    'reports.profit_loss': 'Profit & Loss Report',
    'reports.cash_flow': 'Cash Flow',
    'reports.category_analysis': 'Category Analysis',
    'reports.week': 'Week',
    'reports.month': 'Month',
    'reports.quarter': 'Quarter',
    'reports.year': 'Year',
    'reports.profit_loss_report': 'Profit & Loss Report',
    'reports.current_period': 'Current Period',
    'reports.profit_margin': 'Profit Margin',
    'reports.avg_daily_income': 'Average Daily Income',
    'reports.avg_daily_expenses': 'Average Daily Expenses',
    'reports.total_transactions': 'Total Transactions',
    'reports.no_data': 'No data available',
    'reports.add_transactions_first': 'Add some transactions to generate reports',
    
    // Settings
    'settings.subtitle': 'Manage your account and preferences',
    'settings.profile': 'Profile',
    'settings.language': 'Language',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.profile_info': 'Profile Information',
    'settings.save_changes': 'Save Changes',
    'settings.profile_updated': 'Profile updated successfully',
    'settings.language_preferences': 'Language Preferences',
    'settings.notification_preferences': 'Notification Preferences',
    'settings.email_notifications': 'Email Notifications',
    'settings.email_notifications_desc': 'Receive email updates about your account',
    'settings.tax_reminders': 'Tax Reminders',
    'settings.tax_reminders_desc': 'Get notified about upcoming tax deadlines',
    'settings.security_settings': 'Security Settings',
    'settings.change_password': 'Change Password',
    'settings.change_password_desc': 'Update your account password',
    'settings.two_factor': 'Two-Factor Authentication',
    'settings.two_factor_desc': 'Add an extra layer of security',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
  },
  ru: {
    // Navigation
    'nav.dashboard': 'Панель управления',
    'nav.transactions': 'Операции',
    'nav.reports': 'Отчеты',
    'nav.chatbot': 'ИИ Помощник',
    'nav.settings': 'Настройки',
    'nav.help': 'Помощь',
    'nav.logout': 'Выход',
    
    // Notifications
    'notifications.title': 'Уведомления',
    'notifications.no_notifications': 'Нет уведомлений',
    'notifications.monthly_report': 'Месячный отчет',
    'notifications.report_ready': 'Ваш месячный финансовый отчет готов',
    
    // Dashboard
    'dashboard.title': 'Панель управления',
    'dashboard.subtitle': 'Финансовый обзор вашего бизнеса',
    'dashboard.total_income': 'Общий доход',
    'dashboard.total_expenses': 'Общие расходы',
    'dashboard.net_profit': 'Чистая прибыль',
    'dashboard.recent_transactions': 'Последние операции',
    'dashboard.view_all': 'Показать все',
    'dashboard.quick_actions': 'Быстрые действия',
    'dashboard.new_transaction': 'Новая операция',
    'dashboard.generate_report': 'Создать отчет',
    'dashboard.ask_ai': 'Спросить ИИ',
    'dashboard.expense_chart': 'Расходы по категориям',
    'dashboard.expenses_by_category': 'Расходы по категориям',
    'dashboard.income_vs_expenses': 'Доходы против расходов',
    'dashboard.no_data': 'Нет данных',
    'dashboard.add_transactions_first': 'Добавьте операции для отображения графиков',
    'dashboard.income': 'Доходы',
    'dashboard.expenses': 'Расходы',
    'dashboard.amount': 'Сумма',
    'dashboard.last_30_days': 'Последние 30 дней',
    'dashboard.last_7_days': 'Последние 7 дней',
    'dashboard.last_3_months': 'Последние 3 месяца',
    
    // Chatbot
    'chatbot.subtitle': 'ИИ-анализ финансов и советы',
    'chatbot.welcome': 'Привет! Я ваш ИИ финансовый помощник. Я могу анализировать ваши операции и давать советы по финансам бизнеса. Что вы хотите узнать?',
    'chatbot.ai_assistant': 'ИИ Помощник',
    'chatbot.online': 'Онлайн',
    'chatbot.type_message': 'Введите сообщение...',
    'chatbot.quick_questions': 'Быстрые вопросы:',
    'chatbot.quick_income': 'Сколько у меня доходов?',
    'chatbot.quick_expenses': 'Какие мои самые большие расходы?',
    'chatbot.quick_profit': 'Какая прибыль в этом месяце?',
    'chatbot.quick_advice': 'Дайте финансовый совет',
    'chatbot.income_analysis': 'Ваш общий доход составляет',
    'chatbot.income_positive': 'Отлично! Вы генерируете доходы!',
    'chatbot.income_zero': 'Вы еще не записали доходы. Начните добавлять продажи и доходы.',
    'chatbot.expense_analysis': 'Ваши общие расходы составляют',
    'chatbot.expense_high': 'Ваши расходы превышают доходы. Пересмотрите траты.',
    'chatbot.expense_good': 'Ваши расходы хорошо контролируются по сравнению с доходами.',
    'chatbot.profit_analysis': 'Ваша чистая прибыль составляет',
    'chatbot.profit_positive': 'Отлично! Вы получаете прибыль. Рассмотрите инвестиции в рост.',
    'chatbot.profit_negative': 'У вас убыток. Сосредоточьтесь на увеличении доходов или сокращении расходов.',
    'chatbot.profit_zero': 'Вы в точке безубыточности. Ищите возможности для увеличения прибыльности.',
    'chatbot.category_analysis': 'Ваша самая большая категория расходов',
    'chatbot.no_expenses': 'Вы еще не записали расходы.',
    'chatbot.advice_negative': 'Для улучшения финансов: 1) Пересмотрите и сократите ненужные расходы, 2) Сосредоточьтесь на увеличении продаж, 3) Рассмотрите новые источники дохода.',
    'chatbot.advice_positive': 'Отличное финансовое здоровье! Рассмотрите: 1) Реинвестирование прибыли для роста, 2) Создание резервного фонда, 3) Изучение новых рынков.',
    'chatbot.advice_neutral': 'Для роста бизнеса: 1) Анализируйте самые прибыльные продукты/услуги, 2) Инвестируйте в маркетинг, 3) Оптимизируйте ценообразование.',
    'chatbot.transaction_count': 'У вас',
    'chatbot.transaction_recent': 'Продолжайте отслеживать операции для лучшей аналитики!',
    'chatbot.transaction_none': 'Начните добавлять операции для получения персональных финансовых советов.',
    'chatbot.default_response': 'Я могу помочь анализировать доходы, расходы, прибыль и давать финансовые советы. Попробуйте спросить о финансовых показателях или запросить конкретные советы!',
    
    // Auth
    'auth.login': 'Вход',
    'auth.register': 'Регистрация',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.business_name': 'Название бизнеса',
    'auth.phone': 'Номер телефона',
    'auth.language': 'Язык',
    'auth.create_account': 'Создать аккаунт',
    'auth.have_account': 'Уже есть аккаунт?',
    'auth.no_account': 'Нет аккаунта?',
    'auth.sign_in': 'Войти',
    'auth.sign_up': 'Зарегистрироваться',
    
    // Transactions
    'transactions.subtitle': 'Все операции вашего бизнеса',
    'transactions.new_transaction': 'Новая операция',
    'transactions.edit_transaction': 'Редактировать операцию',
    'transactions.search_placeholder': 'Поиск операций...',
    'transactions.all': 'Все',
    'transactions.income': 'Доход',
    'transactions.expense': 'Расход',
    'transactions.date': 'Дата',
    'transactions.description': 'Описание',
    'transactions.category': 'Категория',
    'transactions.payment_method': 'Способ оплаты',
    'transactions.amount': 'Сумма',
    'transactions.actions': 'Действия',
    'transactions.type': 'Тип',
    'transactions.select_category': 'Выберите категорию',
    'transactions.description_placeholder': 'Введите описание операции',
    'transactions.tax_relevant': 'Налогооблагаемая',
    'transactions.confirm_delete': 'Вы уверены, что хотите удалить эту операцию?',
    'transactions.no_transactions': 'Операций пока нет',
    'transactions.add_first_transaction': 'Добавьте первую операцию для начала',
    'transactions.no_results': 'Операции не найдены',
    'transactions.payment_methods.cash': 'Наличные',
    'transactions.payment_methods.card': 'Банковская карта',
    'transactions.payment_methods.transfer': 'Банковский перевод',
    'transactions.payment_methods.mobile': 'Мобильный платеж',
    'transactions.calendar': 'Календарь',
    'transactions.calendar_view': 'Календарь операций',
    'transactions.has_transactions': 'Есть операции',
    'transactions.selected_date': 'Выбранная дата',
    'transactions.date_range': 'Диапазон дат',
    'transactions.selected_range': 'Выбранный период',
    'transactions.apply_filter': 'Применить фильтр',
    
    // Reports
    'reports.subtitle': 'Детальный анализ вашего бизнеса',
    'reports.profit_loss': 'Отчет о прибылях и убытках',
    'reports.cash_flow': 'Денежный поток',
    'reports.category_analysis': 'Анализ по категориям',
    'reports.week': 'Неделя',
    'reports.month': 'Месяц',
    'reports.quarter': 'Квартал',
    'reports.year': 'Год',
    'reports.profit_loss_report': 'Отчет о прибылях и убытках',
    'reports.current_period': 'Текущий период',
    'reports.profit_margin': 'Маржа прибыли',
    'reports.avg_daily_income': 'Средний дневной доход',
    'reports.avg_daily_expenses': 'Средние дневные расходы',
    'reports.total_transactions': 'Всего операций',
    'reports.no_data': 'Нет данных',
    'reports.add_transactions_first': 'Добавьте операции для создания отчетов',
    
    // Settings
    'settings.subtitle': 'Управление аккаунтом и настройками',
    'settings.profile': 'Профиль',
    'settings.language': 'Язык',
    'settings.notifications': 'Уведомления',
    'settings.security': 'Безопасность',
    'settings.profile_info': 'Информация профиля',
    'settings.save_changes': 'Сохранить изменения',
    'settings.profile_updated': 'Профиль успешно обновлен',
    'settings.language_preferences': 'Языковые настройки',
    'settings.notification_preferences': 'Настройки уведомлений',
    'settings.email_notifications': 'Email уведомления',
    'settings.email_notifications_desc': 'Получать обновления по email',
    'settings.tax_reminders': 'Напоминания о налогах',
    'settings.tax_reminders_desc': 'Получать уведомления о сроках налогов',
    'settings.security_settings': 'Настройки безопасности',
    'settings.change_password': 'Изменить пароль',
    'settings.change_password_desc': 'Обновить пароль аккаунта',
    'settings.two_factor': 'Двухфакторная аутентификация',
    'settings.two_factor_desc': 'Дополнительный уровень безопасности',
    
    // Common
    'common.loading': 'Загрузка...',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.add': 'Добавить',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.export': 'Экспорт',
    'common.confirm': 'Подтвердить',
    'common.yes': 'Да',
    'common.no': 'Нет',
  },
  ky: {
    // Navigation
    'nav.dashboard': 'Башкы бет',
    'nav.transactions': 'Операциялар',
    'nav.reports': 'Отчеттор',
    'nav.chatbot': 'ИИ Жардамчы',
    'nav.settings': 'Жөндөөлөр',
    'nav.help': 'Жардам',
    'nav.logout': 'Чыгуу',
    
    // Notifications
    'notifications.title': 'Билдирүүлөр',
    'notifications.no_notifications': 'Билдирүүлөр жок',
    'notifications.monthly_report': 'Айлык отчет',
    'notifications.report_ready': 'Айлык финансылык отчетуңуз даяр',
    
    // Dashboard
    'dashboard.title': 'Башкы бет',
    'dashboard.subtitle': 'Бизнесиңиздин финансылык абалы',
    'dashboard.total_income': 'Жалпы киреше',
    'dashboard.total_expenses': 'Жалпы чыгым',
    'dashboard.net_profit': 'Таза пайда',
    'dashboard.recent_transactions': 'Акыркы операциялар',
    'dashboard.view_all': 'Баарын көрүү',
    'dashboard.quick_actions': 'Тез аракеттер',
    'dashboard.new_transaction': 'Жаңы операция',
    'dashboard.generate_report': 'Отчет түзүү',
    'dashboard.ask_ai': 'ИИ дан сураңыз',
    'dashboard.expense_chart': 'Категория боюнча чыгымдар',
    'dashboard.expenses_by_category': 'Категория боюнча чыгымдар',
    'dashboard.income_vs_expenses': 'Киреше жана чыгымдар',
    'dashboard.no_data': 'Маалымат жок',
    'dashboard.add_transactions_first': 'Графиктерди көрүү үчүн операцияларды кошуңуз',
    'dashboard.income': 'Киреше',
    'dashboard.expenses': 'Чыгымдар',
    'dashboard.amount': 'Сумма',
    'dashboard.last_30_days': 'Акыркы 30 күн',
    'dashboard.last_7_days': 'Акыркы 7 күн',
    'dashboard.last_3_months': 'Акыркы 3 ай',
    
    // Chatbot
    'chatbot.subtitle': 'ИИ финансылык анализ жана кеңештер',
    'chatbot.welcome': 'Салам! Мен сиздин ИИ финансылык жардамчыңызмын. Мен сиздин операцияларыңызды анализдеп, бизнес финансы боюнча кеңештерди бере алам. Эмнени билгиңиз келет?',
    'chatbot.ai_assistant': 'ИИ Жардамчы',
    'chatbot.online': 'Онлайн',
    'chatbot.type_message': 'Билдирүүңүздү жазыңыз...',
    'chatbot.quick_questions': 'Тез суроолор:',
    'chatbot.quick_income': 'Канча кирешем бар?',
    'chatbot.quick_expenses': 'Эң чоң чыгымдарым кайсылар?',
    'chatbot.quick_profit': 'Бул айда канча пайда?',
    'chatbot.quick_advice': 'Финансылык кеңеш бериңиз',
    'chatbot.income_analysis': 'Сиздин жалпы кирешеңиз',
    'chatbot.income_positive': 'Киреше алганыңыз сонун!',
    'chatbot.income_zero': 'Сиз али киреше жазган жоксуз. Сатуу жана кирешелерди кошуп баштаңыз.',
    'chatbot.expense_analysis': 'Сиздин жалпы чыгымыңыз',
    'chatbot.expense_high': 'Чыгымыңыз кирешеден көп. Чыгымдарды карап чыгыңыз.',
    'chatbot.expense_good': 'Чыгымыңыз кирешеге салыштырмалуу жакшы көзөмөлдө.',
    'chatbot.profit_analysis': 'Сиздин таза пайдаңыз',
    'chatbot.profit_positive': 'Сонун! Пайда алып жатасыз. Өсүүгө инвестиция кылууну ойлонуңуз.',
    'chatbot.profit_negative': 'Учурда зыянда турасыз. Кирешени көбөйтүүгө же чыгымды азайтууга көңүл буруңуз.',
    'chatbot.profit_zero': 'Тең салмакта турасыз. Пайдалуулукту жогорулатуу мүмкүнчүлүктөрүн издеңиз.',
    'chatbot.category_analysis': 'Сиздин эң чоң чыгым категорияңыз',
    'chatbot.no_expenses': 'Сиз али чыгым жазган жоксуз.',
    'chatbot.advice_negative': 'Финансты жакшыртуу үчүн: 1) Керексиз чыгымдарды карап чыгып, кыскартыңыз, 2) Сатууну көбөйтүүгө көңүл буруңуз, 3) Жаңы киреше булактарын карап көрүңүз.',
    'chatbot.advice_positive': 'Мыкты финансылык абал! Карап көрүңүз: 1) Пайданы өсүү үчүн кайра инвестициялоо, 2) Резерв фонд түзүү, 3) Жаңы рынокторду изилдөө.',
    'chatbot.advice_neutral': 'Бизнести өстүрүү үчүн: 1) Эң пайдалуу продукттарды/кызматтарды анализдеңиз, 2) Маркетингге инвестиция кылыңыз, 3) Баа белгилөөнү оптималдаштырыңыз.',
    'chatbot.transaction_count': 'Сизде',
    'chatbot.transaction_recent': 'Жакшыраак анализ үчүн операцияларды көзөмөлдөй бериңиз!',
    'chatbot.transaction_none': 'Жекелештирилген финансылык кеңештерди алуу үчүн операцияларды кошуп баштаңыз.',
    'chatbot.default_response': 'Мен киреше, чыгым, пайданы анализдеп, финансылык кеңештерди бере алам. Финансылык көрсөткүчтөр жөнүндө сураңыз же конкреттүү кеңештерди сураңыз!',
    
    // Auth
    'auth.login': 'Кирүү',
    'auth.register': 'Катталуу',
    'auth.email': 'Email',
    'auth.password': 'Сыр сөз',
    'auth.business_name': 'Бизнес аталышы',
    'auth.phone': 'Телефон номери',
    'auth.language': 'Тил',
    'auth.create_account': 'Аккаунт түзүү',
    'auth.have_account': 'Аккаунтуңуз барбы?',
    'auth.no_account': 'Аккаунтуңуз жокпу?',
    'auth.sign_in': 'Кирүү',
    'auth.sign_up': 'Катталуу',
    
    // Transactions
    'transactions.subtitle': 'Бизнесиңиздин бардык операциялары',
    'transactions.new_transaction': 'Жаңы операция',
    'transactions.edit_transaction': 'Операцияны өзгөртүү',
    'transactions.search_placeholder': 'Операцияларды издөө...',
    'transactions.all': 'Баары',
    'transactions.income': 'Киреше',
    'transactions.expense': 'Чыгым',
    'transactions.date': 'Дата',
    'transactions.description': 'Түшүндүрмө',
    'transactions.category': 'Категория',
    'transactions.payment_method': 'Төлөм ыкмасы',
    'transactions.amount': 'Сумма',
    'transactions.actions': 'Аракеттер',
    'transactions.type': 'Түрү',
    'transactions.select_category': 'Категория тандаңыз',
    'transactions.description_placeholder': 'Операциянын түшүндүрмөсүн киргизиңиз',
    'transactions.tax_relevant': 'Салыктуу',
    'transactions.confirm_delete': 'Бул операцияны өчүрүүнү каалайсызбы?',
    'transactions.no_transactions': 'Операциялар жок',
    'transactions.add_first_transaction': 'Биринчи операцияңызды кошуңуз',
    'transactions.no_results': 'Операциялар табылган жок',
    'transactions.payment_methods.cash': 'Накт акча',
    'transactions.payment_methods.card': 'Банк картасы',
    'transactions.payment_methods.transfer': 'Банк которуу',
    'transactions.payment_methods.mobile': 'Мобилдик төлөм',
    'transactions.calendar': 'Календарь',
    'transactions.calendar_view': 'Операциялар календары',
    'transactions.has_transactions': 'Операциялар бар',
    'transactions.selected_date': 'Тандалган дата',
    'transactions.date_range': 'Дата диапазону',
    'transactions.selected_range': 'Тандалган мезгил',
    'transactions.apply_filter': 'Фильтрди колдонуу',
    
    // Reports
    'reports.subtitle': 'Бизнесиңиздин деталдуу анализи',
    'reports.profit_loss': 'Пайда жана чыгым отчету',
    'reports.cash_flow': 'Акча агымы',
    'reports.category_analysis': 'Категория боюнча анализ',
    'reports.week': 'Жума',
    'reports.month': 'Ай',
    'reports.quarter': 'Квартал',
    'reports.year': 'Жыл',
    'reports.profit_loss_report': 'Пайда жана чыгым отчету',
    'reports.current_period': 'Учурдагы мезгил',
    'reports.profit_margin': 'Пайда маржасы',
    'reports.avg_daily_income': 'Орточо күндүк киреше',
    'reports.avg_daily_expenses': 'Орточо күндүк чыгым',
    'reports.total_transactions': 'Жалпы операциялар',
    'reports.no_data': 'Маалымат жок',
    'reports.add_transactions_first': 'Отчеттор түзүү үчүн операцияларды кошуңуз',
    
    // Settings
    'settings.subtitle': 'Аккаунтту жана жөндөөлөрдү башкаруу',
    'settings.profile': 'Профиль',
    'settings.language': 'Тил',
    'settings.notifications': 'Билдирүүлөр',
    'settings.security': 'Коопсуздук',
    'settings.profile_info': 'Профиль маалыматы',
    'settings.save_changes': 'Өзгөртүүлөрдү сактоо',
    'settings.profile_updated': 'Профиль ийгиликтүү жаңыланды',
    'settings.language_preferences': 'Тил жөндөөлөрү',
    'settings.notification_preferences': 'Билдирүү жөндөөлөрү',
    'settings.email_notifications': 'Email билдирүүлөр',
    'settings.email_notifications_desc': 'Email аркылуу жаңылыктарды алуу',
    'settings.tax_reminders': 'Салык эскертүүлөрү',
    'settings.tax_reminders_desc': 'Салык мөөнөттөрү жөнүндө билдирүүлөрдү алуу',
    'settings.security_settings': 'Коопсуздук жөндөөлөрү',
    'settings.change_password': 'Сыр сөздү өзгөртүү',
    'settings.change_password_desc': 'Аккаунттун сыр сөзүн жаңылоо',
    'settings.two_factor': 'Эки факторлуу аутентификация',
    'settings.two_factor_desc': 'Кошумча коопсуздук деңгээли',
    
    // Common
    'common.loading': 'Жүктөлүүдө...',
    'common.save': 'Сактоо',
    'common.cancel': 'Жокко чыгаруу',
    'common.delete': 'Өчүрүү',
    'common.edit': 'Өзгөртүү',
    'common.add': 'Кошуу',
    'common.search': 'Издөө',
    'common.filter': 'Фильтер',
    'common.export': 'Экспорт',
    'common.confirm': 'Ырастоо',
    'common.yes': 'Ооба',
    'common.no': 'Жок',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('bazar_language') as Language;
    if (savedLanguage && ['en', 'ru', 'ky'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('bazar_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};